export const locations = [
  { id: 1, name: "Norrmalm & City" },
  { id: 2, name: "Södermalm" },
  { id: 3, name: "Östermalm" },
  { id: 4, name: "Vasastan" },
  { id: 5, name: "Kungsholmen" },
  { id: 6, name: "Kista" },
  { id: 7, name: "Nacka & Värmdö" },
  { id: 8, name: "Lidingö" },
  { id: 9, name: "Bromma" },
  { id: 10, name: "Solna & Sundbyberg" },
  { id: 11, name: "Sollentuna" },
  { id: 12, name: "Huddinge" },
  { id: 13, name: "Eskilstuna" },
  { id: 14, name: "Södertälje" },
  { id: 15, name: "Norrköping" },
  { id: 16, name: "Nyköping" },
  { id: 17, name: "Uppsala" },
  { id: 18, name: "Västerås" },
  { id: 19, name: "Täby & Danderyd" },
  { id: 20, name: "Järfälla" },
  { id: 21, name: "Enskede" },
  { id: 22, name: "Ekerö" },
  { id: 23, name: "Vällingby & Hässelby" },
  { id: 24, name: "Årsta" },
];
